[2025-03-21T10:48:01.602+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T10:48:01.650+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2025-03-21T10:37:21.131037+00:00 [queued]>
[2025-03-21T10:48:01.667+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2025-03-21T10:37:21.131037+00:00 [queued]>
[2025-03-21T10:48:01.667+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-21T10:48:01.688+0000] {taskinstance.py:2890} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bigquery_external_table_task> on 2025-03-21 10:37:21.131037+00:00
[2025-03-21T10:48:01.703+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=774) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T10:48:01.707+0000] {standard_task_runner.py:72} INFO - Started process 783 to run task
[2025-03-21T10:48:01.709+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'bigquery_external_table_task', 'manual__2025-03-21T10:37:21.131037+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmpdqdps64o']
[2025-03-21T10:48:01.715+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask bigquery_external_table_task
[2025-03-21T10:48:01.808+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.bigquery_external_table_task manual__2025-03-21T10:37:21.131037+00:00 [running]> on host 4791d3610749
[2025-03-21T10:48:01.932+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='bigquery_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T10:37:21.131037+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T10:37:21.131037+00:00'
[2025-03-21T10:48:01.936+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T10:48:01.959+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-21T10:48:01.960+0000] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-03-21T10:48:01.961+0000] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-03-21T10:48:03.952+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T10:48:03.953+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=bigquery_external_table_task, run_id=manual__2025-03-21T10:37:21.131037+00:00, execution_date=20250321T103721, start_date=20250321T104801, end_date=20250321T104803
[2025-03-21T10:48:04.024+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T10:48:04.058+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T10:48:04.060+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
