[2025-03-24T08:52:24.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T08:52:24.097+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-24T08:52:24.109+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-24T08:52:24.110+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-24T08:52:24.124+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2025-03-21 00:00:00+00:00
[2025-03-24T08:52:24.133+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T08:52:24.135+0000] {standard_task_runner.py:72} INFO - Started process 77 to run task
[2025-03-24T08:52:24.136+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag', 'local_to_gcs_task', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag.py', '--cfg-path', '/tmp/tmp_cjqg8c9']
[2025-03-24T08:52:24.139+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask local_to_gcs_task
[2025-03-24T08:52:24.199+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_gcs_dag.local_to_gcs_task scheduled__2025-03-21T00:00:00+00:00 [running]> on host 4791d3610749
[2025-03-24T08:52:24.297+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_gcs_dag' AIRFLOW_CTX_TASK_ID='local_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-24T08:52:24.298+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T08:52:25.029+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-24T08:52:25.041+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T08:52:25.041+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag, task_id=local_to_gcs_task, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250324T085224, end_date=20250324T085225
[2025-03-24T08:52:25.112+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T08:52:25.140+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T08:52:25.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
