[2025-03-24T12:53:31.143+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T12:53:31.172+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest manual__2025-03-24T12:53:27.368160+00:00 [queued]>
[2025-03-24T12:53:31.184+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_ingestion_postgres_dag.ingest manual__2025-03-24T12:53:27.368160+00:00 [queued]>
[2025-03-24T12:53:31.185+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T12:53:31.201+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): ingest> on 2025-03-24 12:53:27.368160+00:00
[2025-03-24T12:53:31.208+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T12:53:31.210+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-03-24T12:53:31.211+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_postgres_dag', 'ingest', 'manual__2025-03-24T12:53:27.368160+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_postgres_dag.py', '--cfg-path', '/tmp/tmpvlqrq3q5']
[2025-03-24T12:53:31.213+0000] {standard_task_runner.py:105} INFO - Job 151: Subtask ingest
[2025-03-24T12:53:31.269+0000] {task_command.py:467} INFO - Running <TaskInstance: data_ingestion_postgres_dag.ingest manual__2025-03-24T12:53:27.368160+00:00 [running]> on host 244eeec36139
[2025-03-24T12:53:31.377+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_ingestion_postgres_dag' AIRFLOW_CTX_TASK_ID='ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T12:53:27.368160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T12:53:27.368160+00:00'
[2025-03-24T12:53:31.378+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T12:53:31.401+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-24T12:53:31.403+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "ls"']
[2025-03-24T12:53:31.416+0000] {subprocess.py:99} INFO - Output:
[2025-03-24T12:53:31.418+0000] {subprocess.py:106} INFO - ls
[2025-03-24T12:53:31.419+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-24T12:53:31.451+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T12:53:31.452+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_ingestion_postgres_dag, task_id=ingest, run_id=manual__2025-03-24T12:53:27.368160+00:00, execution_date=20250324T125327, start_date=20250324T125331, end_date=20250324T125331
[2025-03-24T12:53:31.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T12:53:31.530+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T12:53:31.532+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
